### PR TITLE
Upgrade scenarios, readme and CI action to OpenSCENARIO 1.1 format

### PR DESCRIPTION
**Pull request by arauschert**
Closes: https://github.com/asam-oss/OSC-ALKS-scenarios/issues/41

Signed-off-by: Andreas Rauschert <andreas.rb.rauschert@bmw.de>

### CODE REVIEW

**Comment by jdsika** [comment]
I am on vacation for 2 weeks. Can the review wait until I tested the setup in combination with the oss simulators?

**Comment by arauschert** [comment]
> I am on vacation for 2 weeks. Can the review wait until I tested the setup in combination with the oss simulators?

Sure. But at the moment only esmini supports OSC 1.1., so I could only test this successfully. For openPASS and CARLA people have to use the old 1.0 scenarios to run from previous release. I added this in the readme.

**Comment by arauschert** [comment]
If I add the coordinate system for the distance calculation with value "road" in CutIn and CutOut scenarios, then the action isn't triggered anymore. Need to investigate or create an issue for esmini.

**Comment by eknabevcc** [comment]
I'd like to investigate. Can you provide the scenario that should but don't work?

**Comment by eknabevcc** [comment]
Ah, maybe it was added in commit https://github.com/asam-oss/OSC-ALKS-scenarios/commit/00f6a84625d37069899cdbc9234c5776982c7250?

**Comment by arauschert** [comment]
> Ah, maybe it was added in commit [00f6a84](https://github.com/asam-oss/OSC-ALKS-scenarios/commit/00f6a84625d37069899cdbc9234c5776982c7250)?

Yes, that's the one. When I change to coordinate sytem "entity" it works. I will change it to entity, since this is closer to the requirement from the regulation (dx).

**Review by jdsika — CHANGES_REQUESTED** [review]
Update date in sceanrios

**Comment by jdsika** [comment]
Rename and merge. LGTM. Note: Add CI tests to detect tabs instead of 4 blanks

**Pull request merged**
